plugins {
	id 'com.android.library'
}

android {
	compileSdk project.targetSDK.toInteger()

	defaultConfig {
		minSdk project.minSDK.toInteger()
		targetSdk project.targetSDK.toInteger()
	}

	buildTypes {
		release {
			minifyEnabled false
			proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
		}
	}
	namespace 'com.mcal.jadx.jadx_plugin_java_input'
}

dependencies {
	api(project(":jadx:jadx-plugins:jadx-plugins-api"))

	// show bytecode disassemble
	implementation 'io.github.skylot:raung-disasm:0.0.2'
}
