plugins {
    id 'com.android.library'
}

android {
    compileSdk project.compileSDK.toInteger()

    defaultConfig {
        minSdk project.minSDK.toInteger()
        targetSdk project.targetSDK.toInteger()
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    namespace 'com.mcal.sun'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation signing.spongy_core
    implementation signing.spongy_prov

    implementation misc.annotations
    implementation misc.annotations_android
}