plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    compileSdk 33
    ndkVersion '24.0.8215888'

    def versionPropsFile = file('version.properties')
    if (versionPropsFile.canRead()) {
        def Properties versionProps = new Properties()
        versionProps.load(new FileInputStream(versionPropsFile))

        def runTasks = gradle.startParameter.taskNames

        def versionMajor = versionProps['VERSION_MAJOR'].toInteger()
        def versionMinor = versionProps['VERSION_MINOR'].toInteger()
        def versionPatch = versionProps['VERSION_PATCH'].toInteger()
        // increment build number on every gradle sync
        def versionBuild = versionProps['VERSION_BUILD'].toInteger() + 1

        // only in release build
        if (':apkEditor:assembleRelease' in runTasks || 'aR' in runTasks) {
            versionPatch++;
            if (versionPatch >= 9) {
                versionPatch = 0;
                versionMinor++;
            }
            if (versionMinor >= 9) {
                versionMinor = 0;
                versionMajor++;
            }
        }

        versionProps['VERSION_MAJOR'] = versionMajor.toString()
        versionProps['VERSION_MINOR'] = versionMinor.toString()
        versionProps['VERSION_PATCH'] = versionPatch.toString()
        versionProps['VERSION_BUILD'] = versionBuild.toString()

        versionProps.store(versionPropsFile.newWriter(), null)

        defaultConfig {
            applicationId "com.mcal.apkeditor.pro"
            minSdk 26
            //noinspection ExpiredTargetSdkVersion
            targetSdk 26
            versionCode versionBuild
            versionName "${versionMajor}.${versionMinor}.${versionPatch}"
            multiDexEnabled true
        }
    } else {
        throw new GradleException("Could not read version.properties!")
    }

    externalNativeBuild {
        cmake {
            version '3.18.1'
            path 'src/main/cpp/CMakeLists.txt'
        }
    }

    buildTypes {
        release {
            ndk {
                abiFilters "arm64-v8a", "x86_64"
            }
            minifyEnabled true
            shrinkResources true
            buildConfigField "boolean", "IS_PRO", "true"
            buildConfigField "boolean", "WITH_SIGN", "true"
            buildConfigField "boolean", "DISPLAY_APP", "true"
            buildConfigField "boolean", "ODEX_PATCH", "true"
            buildConfigField "boolean", "SHOW_AGREEMENT", "true"
            buildConfigField "boolean", "LIMIT_NEW_VERSION", "false"
            buildConfigField "boolean", "PARSER_ONLY", "false"
            buildConfigField "String", "JADX_VERSION", "\"1.4.2+\""
            buildConfigField "String", "APKTOOL_VERSION", "\"2.6.1+\""
            buildConfigField "String", "SMALI_VERSION", "\"2.5.2\""
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

        debug {
            ndk {
                abiFilters "arm64-v8a", "x86_64"
            }
            buildConfigField "boolean", "IS_PRO", "true"
            buildConfigField "boolean", "WITH_SIGN", "true"
            buildConfigField "boolean", "DISPLAY_APP", "true"
            buildConfigField "boolean", "ODEX_PATCH", "true"
            buildConfigField "boolean", "SHOW_AGREEMENT", "true"
            buildConfigField "boolean", "LIMIT_NEW_VERSION", "false"
            buildConfigField "boolean", "PARSER_ONLY", "false"
            buildConfigField "String", "JADX_VERSION", "\"1.4.2+\""
            buildConfigField "String", "APKTOOL_VERSION", "\"2.6.1+\""
            buildConfigField "String", "SMALI_VERSION", "\"2.5.2\""
        }
    }

//    splits {
//        abi {
//            enable true
//            reset()
//            include 'x86_64', 'arm64-v8a'
//            universalApk false
//        }
//    }

    applicationVariants.all { variant ->
        variant.outputs.all {
            if (variant.name == "release") {
                outputFileName = "Apk Editor v.${variant.versionName}-MinAPI${defaultConfig.minSdk}.apk"
            } else {
                outputFileName = "${variant.name}-${variant.versionName}-(${defaultConfig.versionCode}).apk"
            }
        }
    }


    compileOptions {
        // Flag to enable support for the new language APIs
        //coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }
    packagingOptions {
        resources.excludes += 'keys/*'
        resources.excludes += 'license/*'
        resources.excludes += '**/tmp/*'
    }
    lint {
        abortOnError false
        checkReleaseBuilds false
    }
    namespace 'com.mcal.apkeditor'
}

configurations {
    debugImplementation.exclude group: "junit", module: "junit"
}


dependencies {
    def latestFastAdapterRelease = "5.6.0"

    implementation project(':androlib')
    implementation project(':jadx')
    implementation project(':smali')
    implementation project(':apklib')
    implementation project(':common')
    implementation project(':codeeditor')
    implementation project(':pngeditor')
    implementation project(':imageview')
    implementation project(':apksigner')
    implementation project(':dataeditor')
    implementation project(':crashreporter')
    implementation project(':patchview')
    implementation project(':melissa')
    implementation project(':manifestparser')
    implementation project(':net-manager')

    implementation project(':libraries')

    implementation 'androidx.core:core-ktx:1.9.0'
    implementation 'androidx.appcompat:appcompat:1.5.1'
    implementation 'androidx.preference:preference-ktx:1.2.0'
    implementation 'androidx.drawerlayout:drawerlayout:1.1.1'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.5.1'
    implementation 'com.google.android.material:material:1.6.1'

    implementation 'org.jetbrains:annotations:23.0.0'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.1'

    implementation 'com.google.guava:guava:31.1-android'
    implementation 'org.antlr:antlr-runtime:3.5.2'

    implementation "androidx.constraintlayout:constraintlayout:2.1.4"

    implementation "com.mikepenz:fastadapter:${latestFastAdapterRelease}"
    implementation "androidx.datastore:datastore-preferences:1.0.0"

    // LeakCanary
    debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.9.1'

    //coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'
}