plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}
def Properties versionProps = new Properties()

android {
    compileSdk project.compileSDK.toInteger()
    ndkVersion '24.0.8215888'

    def versionPropsFile = file('version.properties')
    if (versionPropsFile.canRead()) {

        versionProps.load(new FileInputStream(versionPropsFile))

        def runTasks = gradle.startParameter.taskNames

        def versionMajor = versionProps['VERSION_MAJOR'].toInteger()
        def versionMinor = versionProps['VERSION_MINOR'].toInteger()
        def versionPatch = versionProps['VERSION_PATCH'].toInteger()
        // increment build number on every gradle sync
        def versionBuild = versionProps['VERSION_BUILD'].toInteger() + 1
        // versionProps['CACHED_VERSION']
        // Используется для поддержки Instant Run в дебаг режиме. Потому что при инкрементальном обновлении постоянно меняется versionCode
        // в AndroidManifest.xml из-за чего применение изменений становится невозможным без полной установки приложения.
        // Этот костыль берет для дебаг версии versionCode с последней релизной сборки и не меняет его на протяжении всего процесса debug сборок,
        // обновляется на новое, в тот момент, когда происходит релизная сборка проекта


        // only in release build
        if (':apkEditor:assembleRelease' in runTasks || 'aR' in runTasks) {
            versionPatch++;
            if (versionPatch >= 9) {
                versionPatch = 0;
                versionMinor++;
            }
            if (versionMinor >= 9) {
                versionMinor = 0;
                versionMajor++;
            }
            // sync if release
            versionProps['CACHED_VERSION'] = versionBuild.toString()
        }

        versionProps['VERSION_MAJOR'] = versionMajor.toString()
        versionProps['VERSION_MINOR'] = versionMinor.toString()
        versionProps['VERSION_PATCH'] = versionPatch.toString()
        versionProps['VERSION_BUILD'] = versionBuild.toString()

        versionProps.store(versionPropsFile.newWriter(), null)

        defaultConfig {
            applicationId "com.mcal.apkeditor.pro"
            minSdk project.minSDK.toInteger()
            //noinspection ExpiredTargetSdkVersion
            targetSdk project.targetSDK.toInteger()
            versionCode versionBuild
            versionName "${versionMajor}.${versionMinor}.${versionPatch}"
            multiDexEnabled true

            resConfigs 'ar', 'be', 'cs', 'de', 'es', 'fa', 'fr', 'hu', 'it',
                        'iw', 'nl', 'pl', 'pt', 'ru', 'sk', 'tr', 'uk', 'vi', 'zh'
        }
    } else {
        throw new GradleException("Could not read version.properties!")
    }

    buildTypes {
        release {
            defaultConfig.versionCode = versionProps['VERSION_BUILD'].toInteger()

            minifyEnabled true
            shrinkResources true
            buildConfigField "boolean", "SHOW_AGREEMENT", "true"
            buildConfigField "String", "JADX_VERSION", "\"1.4.2+\""
            buildConfigField "String", "APKTOOL_VERSION", "\"2.6.1+\""
            buildConfigField "String", "SMALI_VERSION", "\"2.5.2\""
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

        debug {
            defaultConfig.versionCode = versionProps['CACHED_VERSION'].toInteger()

            ndk {
                abiFilters "arm64-v8a", "x86_64"
            }
            buildConfigField "boolean", "SHOW_AGREEMENT", "false"
            buildConfigField "String", "JADX_VERSION", "\"1.4.2+\""
            buildConfigField "String", "APKTOOL_VERSION", "\"2.6.1+\""
            buildConfigField "String", "SMALI_VERSION", "\"2.5.2\""
        }
    }

//    splits {
//        abi {
//            enable true
//            reset()
//            include 'x86_64', 'arm64-v8a'
//            universalApk false
//        }
//    }

//    task runSign(type:Exec) {
//        println "Run Jiagu Tool"
//        commandLine = ['cmd','/c', jiagu_dir]
//    }

    applicationVariants.all { variant ->
        variant.outputs.all {
            if (variant.name == "release") {
                outputFileName = "Apk Editor v.${variant.versionName}-Min API ${defaultConfig.minSdk}.apk"
            } else {
                outputFileName = "${variant.name}-${variant.versionName}-milestone-(${versionCode}).apk"
            }
        }
    }


    compileOptions {
        // Flag to enable support for the new language APIs
        //coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }
    packagingOptions {
        resources.excludes += 'keys/*'
        resources.excludes += 'license/*'
        resources.excludes += '**/tmp/*'
        resources.excludes += 'org/eclipse/*'
        resources.excludes += 'android/*'
    }
    lint {
        abortOnError false
        checkReleaseBuilds false
    }
    buildFeatures {
        viewBinding true
    }
    namespace 'com.mcal.apkeditor'
}

configurations {
    debugImplementation.exclude group: "junit", module: "junit"
}


dependencies {
    implementation tools.apktool
    implementation project(':jadx:jadx-plugins:jadx-dex-input')
    implementation project(':core')
    implementation project(':feature:code-editor')
    implementation project(':feature:imageview')
    implementation project(':apksigner')
    implementation project(':feature:data-editor')
    implementation project(':feature:crashreporter')
    implementation project(':feature:patchview')
    implementation project(':melissa')
    implementation project(':feature:manifestparser')
    implementation project(':feature:net-manager')
    implementation project(':feature:bsh-engine')
    implementation project(':feature:colormixer')

    implementation tools.dexlib2
    implementation tools.smali
    implementation tools.baksmali

    implementation jetpack.core
    implementation jetpack.appcompat
    implementation jetpack.preference
    implementation jetpack.mvvm_vm
    implementation jetpack.mvvm_ld
    implementation jetpack.fragment
    implementation jetpack.navigation

    implementation jetpack.material

    implementation misc.annotations
    implementation misc.gson
    implementation misc.coroutines_core

    implementation misc.guava
    implementation misc.antlr

    implementation jetpack.constraint

    implementation ui.fastadapter
    implementation ui.fastadapter_binding

    implementation jetpack.vp2
    implementation jetpack.preferences
    implementation jetpack.preferences_core

    // LeakCanary
    debugImplementation misc.leaks
}