pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

include ':apklib'
include ':core'
include ':imageview'
include ':apkEditor'
include ':sqliteutil'
include ':codeeditor'
include ':dataeditor'
include ':crashreporter'
include ':apksigner'
include ':patchview'
include ':xpp3'
include ':androlib'
include ':smali'
include(':bsh-engine')

include ':jadx:jadx-core',
        ':jadx:jadx-cli',
        ':jadx:jadx-plugins',
        ':jadx:jadx-plugins:jadx-plugins-api',
        ':jadx:jadx-plugins:jadx-dex-input',
        ':jadx:jadx-plugins:jadx-java-input',
        ':jadx:jadx-plugins:jadx-raung-input',
        ':jadx:jadx-plugins:jadx-smali-input',
        ':jadx:jadx-plugins:jadx-java-convert'


include ':androlib:brut.j.common',
        ':androlib:brut.j.util',
        ':androlib:brut.j.dir',
        ':androlib:brut.apktool:apktool-lib',
        ':androlib:brut.apktool:apktool-cli'

include ':manifestparser'
include ':net-manager'

include ':libraries'
include ':melissa'

include ':sun'
include ':features:selectapk'
