include ':apklib'
include ':httpserver'
include ':pngeditor'
include ':common'
include ':imageview'
include ':apkEditor'
include ':applistutil'
include ':sqliteutil'
include ':codeeditor'
include ':dataeditor'
include ':crashreporter'
include ':apksigner'
include ':xpp3'
include ':androlib'
include ':androlib-legacy'
include ':melissa'
include ':smali'
include ':smali-legacy'
include ':jadx'
include ':jadx-legacy'

include ':libraries'
