pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

include ':apklib'
include ':common'
include ':imageview'
include ':apkEditor'
include ':sqliteutil'
include ':codeeditor'
include ':dataeditor'
include ':crashreporter'
include ':apksigner'
include ':patchview'
include ':xpp3'
include ':androlib'
include ':smali'

include ':jadx:jadx-core'
include ':jadx:jadx-cli'
include ':jadx:jadx-plugins'
include ':jadx:jadx-plugins:jadx-plugins-api'
include ':jadx:jadx-plugins:jadx-dex-input'
include ':jadx:jadx-plugins:jadx-java-input'
include ':jadx:jadx-plugins:jadx-raung-input'
include ':jadx:jadx-plugins:jadx-smali-input'
include ':jadx:jadx-plugins:jadx-java-convert'

include ':manifestparser'
include ':net-manager'

include ':libraries'
include ':melissa'
