plugins {
    id 'com.android.library'
}
android {
    compileSdk project.targetSDK.toInteger()

    defaultConfig {
        minSdk project.minSDK.toInteger()
        targetSdk project.targetSDK.toInteger()
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
    namespace 'com.mcal.androlib.cli'
}

dependencies {
    implementation project(flat.core)

    implementation project(flat.androlib)

    implementation misc.commons_cli
    implementation misc.annotations
}