configurations.maybeCreate("default")

artifacts.add("default", file('kellinwood-logging-android-1.4.jar'))
artifacts.add("default", file('kellinwood-logging-lib-1.1.jar'))
artifacts.add("default", file('zipio-lib-1.8.jar'))
artifacts.add("default", file('zipsigner-lib-1.17.jar'))
artifacts.add("default", file('zipsigner-lib-optional-1.17.jar'))