[versions]
android-apktool = "2.7.0.8"
androidx-activity = "1.8.2"
androidx-appcompat = "1.7.1"
androidx-annotation = "1.7.1"
annotations = "24.1.0"
antlr-runtime = "3.5.3"
smali = "3.0.10"
androidx-coordinatorlayout = "1.2.0"
androidx-core-ktx = "1.12.0"
androidx-navigation-fragment-ktx = "2.7.6"
androidx-navigation-ui-ktx = "2.7.6"
androidx-preference-ktx = "1.2.1"
commons-text = "1.9"
core = "1.58.0.0"
crash = "2.4.0"
androidx-datastore-preferences-core = "1.0.0"
androidx-datastore-preferences = "1.0.0"
fastadapter = "5.7.0"
guava = "31.0.1-android"
kotlinx-coroutines-core = "1.7.3"
gson = "2.10.1"
leakcanary-android = "2.12"
library = "1.3.0"
androidx-lifecycle-viewmodel-ktx = "2.6.2"
material = "1.14.0-alpha09"
play-services-base = "18.2.0"
utilcodex = "1.30.6"
androidx-viewpager2 = "1.0.0"
webview = "1.0.9"

[libraries]
android-apktool = { module = "com.github.TimScriptov:Android-ApkTool-Library", version.ref = "android-apktool" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-datastore-preferences-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "androidx-datastore-preferences-core" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore-preferences" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle-viewmodel-ktx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle-viewmodel-ktx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle-viewmodel-ktx" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation-fragment-ktx" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "androidx-activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "androidx-viewpager2" }
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }
antlr-runtime = { module = "org.antlr:antlr-runtime", version.ref = "antlr-runtime" }
baksmali = { module = "com.android.tools.smali:smali-baksmali", version.ref = "smali" }
androidx-coordinatorlayout = { module = "androidx.coordinatorlayout:coordinatorlayout", version.ref = "androidx-coordinatorlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
commons-text = { module = "org.apache.commons:commons-text", version.ref = "commons-text" }
core = { module = "com.madgag.spongycastle:core", version.ref = "core" }
customactivitycrash = { module = "cat.ereza:customactivityoncrash", version.ref = "crash" }
dexlib2 = { module = "com.android.tools.smali:smali-dexlib2", version.ref = "smali" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation-ui-ktx" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "androidx-preference-ktx" }
fastadapter = { module = "com.mikepenz:fastadapter", version.ref = "fastadapter" }
fastadapter-extensions-binding = { module = "com.mikepenz:fastadapter-extensions-binding", version.ref = "fastadapter" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary-android" }
library = { module = "me.zhanghai.android.fastscroll:library", version.ref = "library" }
material = { module = "com.google.android.material:material", version.ref = "material" }
play-services-base = { module = "com.google.android.gms:play-services-base", version.ref = "play-services-base" }
prov = { module = "com.madgag.spongycastle:prov", version.ref = "core" }
smali = { module = "com.android.tools.smali:smali", version.ref = "smali" }
uidesigner = { module = "com.github.TimScriptov.App-UI-Designer:uidesigner", version.ref = "webview" }
utilcodex = { module = "com.blankj:utilcodex", version.ref = "utilcodex" }
webview = { module = "com.github.TimScriptov.App-UI-Designer:webview", version.ref = "webview" }

[plugins]