plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

android {
    compileSdk project.compileSDK.toInteger()

    defaultConfig {
        minSdk project.minSDK.toInteger()
        targetSdk project.targetSDK.toInteger()
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
    buildFeatures {
        viewBinding true
    }
    namespace 'com.mcal.common'
}

dependencies {
    implementation project(':feature:crashreporter')
    implementation project(":melissa")
    implementation project(':sun')

    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.preference:preference-ktx:1.2.0'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'

    implementation 'com.google.android.material:material:1.8.0'
    implementation 'com.google.android.gms:play-services-base:18.1.0'

    implementation 'org.jetbrains:annotations:24.0.0'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4'

    implementation 'com.blankj:utilcodex:1.30.6'
    implementation 'org.apache.commons:commons-text:1.10.0'

    implementation "androidx.datastore:datastore-preferences:1.0.0"
    implementation "androidx.datastore:datastore-preferences-core:1.0.0"
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:2.5.1"
}