package com.mcal.apkeditor

import android.content.Context
import android.util.Log
import brut.androlib.Androlib
import brut.androlib.options.BuildOptions
import com.mcal.androlib.util.Logger
import com.mcal.apkeditor.ce.IApkMaking
import com.mcal.apkeditor.pro.DexEncoder
import com.mcal.apkeditor.smali.ISmaliAssembleCallback
import com.mcal.apkeditor.utils.AssetsInstaller
import com.mcal.apksigner.ApkSigner
import com.mcal.common.data.Preferences
import com.mcal.common.fastzip.FastZip
import com.mcal.common.utils.createNewFile
import com.mcal.common.utils.recursiveModifiedTime
import com.mcal.common.utilsOld.*
import com.mcal.common.utilsOld.ITaskCallback.TaskStepInfo
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import java.io.File
import java.io.IOException
import java.lang.reflect.InvocationTargetException
import java.util.logging.Level
import kotlin.coroutines.CoroutineContext
import kotlin.math.max


/**
 * @param ctx             Context
 * @param decodedFilePath path store all the decoded files
 * @param apkPath         target apk path
 */
class ApkComposeThreadNew(
    private val ctx: Context,
    decodedFilePath: String,
    apkPath: String
) : ComposeThread(), ISmaliAssembleCallback, Logger {
    private val binRootPath: String
    private val aaptPath: String
    private val aaptPath2: String
    private val androidJarPath: String
    private val decodedFilePath: String
    private val targetApkPath: String // Target APK path
    private val resourceApkPath: String // if res modified, store the apk generated by aapt

    // Record all the dex file replaces
    private val builtDexFiles: MutableMap<String, String> = HashMap()

    // Samli file modified or not
    private val modifiedSmaliFolders: MutableList<String> = ArrayList()
    private val stepInfo: TaskStepInfo

    // Last time updating the smali assemble info
    private val lastUpdateAssembleTime: Long = 0

    // Before merge, call the extra maker
    var replacedFiles: MutableMap<String, String> = HashMap()
    var addedFiles: MutableMap<String, String> = HashMap()

    // Indicate succeed or not
    private var succeed = false
    var errMessage: String? = null
        private set
    private var taskCallback: ITaskCallback? = null

    // Flag to control run or not
    private var stopFlag = false
    private var bSignApk = false
    private var extraMaker: IApkMaking? = null

    private var runningJob = Job()

    override val coroutineContext: CoroutineContext
        get() = Dispatchers.Main + runningJob

    // resReplaces contains non-xml replaces
    // resFileModified means res added/deleted, or xml changed
    override fun setModification(
        strModified: Boolean,
        manifestModified: Boolean,
        resFileModified: Boolean,
        modifiedSmaliFolders: List<String>?,
        addedFiles: MutableMap<String, String>?,
        replacedFiles: MutableMap<String, String>?,
        deletedFiles: MutableSet<String>?,
        fileEntry2ZipEntry: Map<String, String>?,
        bSignApk: Boolean
    ) {
        this.bSignApk = bSignApk
    }

    override fun execute() = launch {
        doInBackground()
    }

    private suspend fun doInBackground(): Boolean = withContext(Dispatchers.IO) {
        val startTime = System.currentTimeMillis()
        // Make sure build directory is created
        val buildDir = File("$decodedFilePath/build")
        if (!buildDir.exists()) {
            if (buildDir.mkdir()) {
                Log.e(javaClass.name, "$buildDir created")
            }
        }
        if (Preferences.isApkToolCompiler()) {
            do {
                val binFolder = File(ctx.filesDir.toString() + "/bin")
                val options = BuildOptions()
                options.useAapt2 = Preferences.isAapt2(ctx)
                options.aaptPath = binFolder.toString() + File.separator + if (Preferences.isAapt2(ctx)) "aapt2" else "aapt"
                options.frameworkFolderLocation = binFolder.path
                val androlib = Androlib(options, this@ApkComposeThreadNew)
                try {
                    val tmp = File.createTempFile("APKTOOL", null)
                    stepInfo.stepTotal = 4
                    try {
                        setNextStep("Preparing...")
                        AssetsInstaller(ctx).install()
                    } catch (e: Exception) {
                        errMessage = e.message
                    }
                    setNextStep("Compiling...")
                    androlib.build(File(decodedFilePath), tmp)
                    setNextStep("Signing...")
                    if (!signApk(tmp.path)) {
                        break
                    }
                } catch (e: Exception) {
                    e.printStackTrace()
                    errMessage = e.message
                    break
                }
                // Clean up
                if (stopFlag) {
                    errMessage = "User request to stop"
                    break
                }
                setNextStep(ctx.getString(R.string.cleanup))
                cleanup()
                succeed = true
            } while (false)
        } else {
            val rebuildResource = needRebuildResource()
            checkSmaliModification()
            stepInfo.stepTotal = 0

            // Prepare
            stepInfo.stepTotal += 1

            // Need to build resource
            if (rebuildResource) {
                stepInfo.stepTotal += 1
            }
            // Merge
            stepInfo.stepTotal += 1
            // For DEX assembling
            if (modifiedSmaliFolders.isNotEmpty()) {
                stepInfo.stepTotal += modifiedSmaliFolders.size
            }
            // Sign
            if (BuildConfig.WITH_SIGN && bSignApk) {
                stepInfo.stepTotal += 1
            }
            // Cleanup
            stepInfo.stepTotal += 1
            do {
                // XML/String/Manifest modified, requires re-compiling
                if (rebuildResource) {
                    if (stopFlag) {
                        errMessage = "User request to stop"
                        break
                    }
                    setNextStep(ctx.getString(R.string.compose))
                    try {
                        setNextStep("Preparing...")
                        AssetsInstaller(ctx).install()
                    } catch (e: Exception) {
                        errMessage = e.message
                    }

                    // Compose resource and extract files
                    if (stopFlag) {
                        errMessage = "User request to stop"
                        break
                    }
                    if (!composeResource()) {
                        break
                    }
                }

                // Assemble DEX files
                builtDexFiles.clear()
                if (modifiedSmaliFolders.isNotEmpty()) {
                    var assembleError = false
                    for (smaliFolder in modifiedSmaliFolders) {
                        val smaliPath = "$decodedFilePath/$smaliFolder"
                        val dexName = getDexNameBySmaliFolder(smaliFolder)
                        setNextStep(ctx.getString(R.string.assemble_dex_file) + ": " + dexName)
                        try {
                            // Log.d("DEBUG", "Assemble " + smaliPath + " to " + dexName);
                            assembleSmali(smaliPath, dexName)
                        } catch (e: Throwable) {
                            e.printStackTrace()
                            errMessage = e.message
                            assembleError = true
                            break
                        }
                        if (stopFlag) {
                            errMessage = "User request to stop"
                            assembleError = true
                            break
                        }
                    }
                    if (assembleError) break
                }

                // Merge
                if (stopFlag) {
                    errMessage = "User request to stop"
                    break
                }
                setNextStep(ctx.getString(R.string.merge))
                try {
                    mergeApk()
                } catch (e: Exception) {
                    e.printStackTrace()
                    errMessage = ctx.getString(R.string.merge) + ": " + e.message
                    break
                }

                // Sign or not
                if (BuildConfig.WITH_SIGN && bSignApk) {
                    if (stopFlag) {
                        errMessage = "User request to stop"
                        break
                    }
                    setNextStep(ctx.getString(R.string.sign))
                    if (!signApk(targetApkPath.replace(".apk", "_unsigned.apk"))) {
                        break
                    }
                }

                // Clean up
                if (stopFlag) {
                    errMessage = "User request to stop"
                    break
                }
                setNextStep(ctx.getString(R.string.cleanup))
                cleanup()

                // For free version, make sure it longer enough, so that ad could be loaded
                if (!BuildConfig.IS_PRO) {
                    val curTime = System.currentTimeMillis()
                    if (curTime - startTime < 7500) {
                        try {
                            // delay(7500 - (curTime - startTime))
                        } catch (e: InterruptedException) {
                            e.printStackTrace()
                        }
                    }
                }
                succeed = true
            } while (false)
        }
        if (!stopFlag) {
            if (succeed) {
                taskCallback?.taskSucceed()
            } else {
                taskCallback?.taskFailed(errMessage)
            }
        }
        return@withContext true
    }

    private fun getLastModifyTime(file: File): Long {
        return if (file.exists()) {
            file.lastModified()
        } else {
            0 // If file does not exist, then return 0
        }
    }

    // Collect all modified smali folders
    private fun checkSmaliModification() {
        val decodeDir = File(decodedFilePath)
        val files = decodeDir.listFiles()
        if (files != null) {
            for (f in files) {
                if (!f.isDirectory) {
                    continue
                }
                val dirName = f.name
                if (dirName == "smali" || dirName.startsWith("smali_")) {
                    val dexName = getDexNameBySmaliFolder(dirName)
                    val dexTime1 = getLastModifyTime(File("$decodedFilePath/$dexName"))
                    val dexTime2 = getLastModifyTime(File("$decodedFilePath/build/$dexName"))
                    val dexTime = max(dexTime2, dexTime1)
                    val smaliTime = recursiveModifiedTime(f)
                    // Means smali code is modified
                    if (smaliTime > dexTime) {
                        modifiedSmaliFolders.add(dirName)
                    }
                }
            }
        }
    }

    private fun getDexNameBySmaliFolder(smaliFolder: String): String {
        if ("smali" == smaliFolder) {
            return "classes.dex"
        }
        return if (smaliFolder.startsWith("smali_")) {
            smaliFolder.substring("smali_".length) + ".dex"
        } else {
            "$smaliFolder.dex"
        }
    }

    private fun setNextStep(description: String) {
        stepInfo.stepIndex += 1
        stepInfo.stepDescription = description
        taskCallback?.setTaskStepInfo(stepInfo)
    }

    // Assemble smali to DEX (build/classes.dex)
    @Throws(Throwable::class)
    private fun assembleSmali(smaliFilePath: String, dexFileName: String) {
        val decodeDir = File(decodedFilePath)
        val buildDir = File(decodeDir, "build")
        if (!buildDir.exists()) {
            if (buildDir.mkdir()) {
                Log.e(javaClass.name, "$buildDir created")
            }
        }
        val dexFile = File(buildDir, dexFileName)
        val dexFilePath = dexFile.path

        // Log.d("DEBUG", "assemble " + smaliFilePath + " to " + dexFilePath +
        // ", dexFileName=" + dexFileName);

        // Invoke DexEncoder.smali2Dex
        try {
            val start = System.currentTimeMillis()
            DexEncoder.smali2Dex(smaliFilePath, dexFilePath, this)
            Log.i("DEBUG", "Encode time=" + (System.currentTimeMillis() - start))

            // Record built dex files
            builtDexFiles[dexFileName] = dexFilePath
        } catch (e: InvocationTargetException) {
            throw e.targetException
        }
    }

    private fun cleanup() {
        val cr = CommandRunner()
        try {
            val tmpDir = SDCard.getRootDirectory() + "/ApkEditor/tmp"
            cr.runCommand("rm -rf $tmpDir", null, 10000)
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }

    private fun mergeApk() {
        extraMaker?.let { extra ->
            try {
                extra.prepareReplaces(ctx, resourceApkPath, replacedFiles)  // Note: currently not support description update
                { strDesc: String? -> }
            } catch (e: Exception) {
                e.printStackTrace()
            }
        }

        // Collect files need to be added
        val assetsDir = File("$decodedFilePath/assets")
        if (assetsDir.exists()) {
            collectFiles(addedFiles, assetsDir, "assets/")
        }
        val libDir = File("$decodedFilePath/lib")
        if (libDir.exists()) {
            collectFiles(addedFiles, libDir, "lib/")
        }
        val libsDir = File("$decodedFilePath/libs")
        if (libsDir.exists()) {
            collectFiles(addedFiles, libsDir, "libs/")
        }
        val unknownDir = File("$decodedFilePath/unknown")
        if (unknownDir.exists()) {
            collectFiles(addedFiles, unknownDir, "")
        }
        // DEX
        collectDexFiles(addedFiles)

        // Transform to string
        val sb = StringBuilder()
        var addLen = 0
        for ((key, value) in addedFiles) {
            sb.append(key)
            sb.append('\n')
            sb.append(value)
            sb.append('\n')
            addLen += key.toByteArray().size + value.toByteArray().size + 2
        }
        val sb2 = StringBuilder()
        var replaceLen = 0
        for ((key, value) in replacedFiles) {
            sb2.append(key)
            sb2.append('\n')
            sb2.append(value)
            sb2.append('\n')
            replaceLen += key.toByteArray().size + value.toByteArray().size + 2
        }

        try {
            FastZip.repack(resourceApkPath, targetApkPath.replace(".apk", "_unsigned.apk"), replacedFiles, addedFiles, null)
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }

    private fun collectDexFiles(filesToAdd: MutableMap<String, String>) {
        filesToAdd.putAll(builtDexFiles)
        val decodeDir = File(decodedFilePath)
        decodeDir.listFiles()?.let { files ->
            for (f in files) {
                val name = f.name
                if (f.isFile && name.endsWith(".dex")) {
                    val dex = File("$decodedFilePath/build/$name")
                    if (dex.isFile && dex.exists()) {
                        filesToAdd[name] = dex.path
                        replacedFiles[name] = dex.path
                    } else {
                        filesToAdd[name] = f.path
                        replacedFiles[name] = f.path
                    }
                }
            }
        }
    }

    private fun collectFiles(relPath2AbsPath: MutableMap<String, String>, dir: File, relPath: String) {
        dir.listFiles()?.let { files ->
            for (f in files) {
                if (f.isFile) {
                    relPath2AbsPath[relPath + f.name] = f.path
                    replacedFiles[relPath + f.name] = f.path
                } else if (f.isDirectory) {
                    collectFiles(relPath2AbsPath, f, relPath + f.name + "/")
                }
            }
        }
    }

    private fun needRebuildResource(): Boolean {
        var buildResource = true

        // To check if need to build the resource
        val apkFile = File(resourceApkPath)
        if (apkFile.isFile && apkFile.exists()) {
            val resModifyTime = recursiveModifiedTime(
                arrayOf(
                    File("$decodedFilePath/res"),
                    File("$decodedFilePath/AndroidManifest.xml")
                )
            )
            val apkTime = apkFile.lastModified()
            if (apkTime > resModifyTime) {
                buildResource = false
            }
        }
        return buildResource
    }

    private fun signApk(inApk: String): Boolean {
        try {
            ApkSigner().signApk(inApk, targetApkPath)
            return true
        } catch (e: Exception) {
            val strHeader = ctx.resources.getString(R.string.sign_error)
            errMessage = strHeader + e.message
        }
        return false
    }

    private fun composeResource(): Boolean {
        return try {
            if (Preferences.isAapt2(ctx)) aapt2() else aapt()
        } catch (e: IOException) {
            e.printStackTrace()
            false
        }
    }

    private fun aapt(): Boolean {
        val noVersionVectorOption = Preferences.getNoVersionVectorOption(aaptPath)
        val paramList: MutableList<String> = ArrayList()
        paramList.add(aaptPath)
        paramList.add("package")
        paramList.add("-f")
        paramList.add("-I")
        paramList.add(androidJarPath)
        paramList.add("-S")
        paramList.add("$decodedFilePath/res")
        paramList.add("-M")
        paramList.add("$decodedFilePath/AndroidManifest.xml")
        paramList.add("-F")
        paramList.add(resourceApkPath)
        if (noVersionVectorOption) {
            paramList.add("--no-version-vectors")
        }
        val cr = CommandRunner()
        val ret = cr.runCommand(paramList.toTypedArray(), null, null, 300 * 1000, true)
        //Log.e("DEBUG", "aapt Time: " + (System.currentTimeMillis() - startTime) / 1000.0 + " seconds");
        LOGGER.info("stdout: " + cr.stdOut + ", ret=" + ret)
        if (!ret) {
            LOGGER.info("stderr: " + cr.stdError)
            errMessage = cr.stdError
            return false
        }
        return true
    }

    @Throws(IOException::class)
    fun aapt2(): Boolean {
        val noVersionVectorOption = Preferences.getNoVersionVectorOption(aaptPath2)
        val args = ArrayList<String>()
        //compile resources
        args.add(aaptPath2)
        args.add("compile")
        args.add("--dir")
        args.add("$decodedFilePath/res")
        args.add("-o")
        val resPath = File(decodedFilePath, "build")
        if (resPath.mkdir()) {
            Log.e(javaClass.name, File(decodedFilePath, "build").toString() + "created")
        }
        val outputPath = createNewFile(resPath, "resources.zip")
        args.add(outputPath.absolutePath)
        val startTime = System.currentTimeMillis()
        val cr = CommandRunner()
        val ret = cr.runCommand(args.toTypedArray(), null, null, 300 * 1000, true)
        LOGGER.info("stdout: " + cr.stdOut + ", ret=" + ret)
        if (!ret) {
            LOGGER.info("stderr: " + cr.stdError)
            errMessage = cr.stdError
            return false
        }
        args.clear()

        //link resources
        args.add(aaptPath2)
        args.add("link")
        args.add("--allow-reserved-package-id")
        if (noVersionVectorOption) {
            args.add("--no-version-vectors")
        }
        args.add("--no-version-transitions")
        args.add("--auto-add-overlay")
        args.add("-I")
        args.add(androidJarPath)

        //add compiled resources
        val resources = resPath.listFiles()
        if (resources != null) {
            for (file in resources) {
                if (file.isDirectory || file.name == "resources.zip") {
                    continue
                }
                args.add("-R")
                args.add(file.absolutePath)
            }
        }
        val projectZip = File(resPath, "resources.zip")
        if (projectZip.exists()) {
            args.add("-R")
            args.add(projectZip.absolutePath)
        }
        args.add("--manifest")
        args.add("$decodedFilePath/AndroidManifest.xml")
        args.add("-o")
        args.add(resourceApkPath)
        val cr2 = CommandRunner()
        val ret2 = cr2.runCommand(args.toTypedArray(), null, null, 300 * 1000, true)
        Log.e("DEBUG", "aapt Time: " + (System.currentTimeMillis() - startTime) / 1000.0 + " seconds")
        LOGGER.info("stdout: " + cr2.stdOut + ", ret=" + ret2)
        if (!ret2) {
            LOGGER.info("stderr: " + cr2.stdError)
            errMessage = cr.stdError
            return false
        }
        return true
    }

    override fun setTaskCallback(callback: ITaskCallback?) {
        this.taskCallback = callback
    }

    override fun updateAssembledFiles(assembledFiles: Int, totalFiles: Int) {
        val curTime = System.currentTimeMillis()
        if (curTime > lastUpdateAssembleTime + 500) {
            val fmt = ctx.getString(R.string.assemble_dex_detail)
            stepInfo.stepDescription = String.format(fmt, assembledFiles, totalFiles)
            taskCallback?.setTaskStepInfo(stepInfo)
        }
    }

    override fun stopRunning() {
        stopFlag = true
        runningJob.cancel()
    }

    override fun setExtraMaker(extraMaker: IApkMaking?) {
        this.extraMaker = extraMaker
    }

    init {
        val fileDir = ctx.filesDir
        val rootDirectory = fileDir.absolutePath
        binRootPath = "$rootDirectory/bin"
        aaptPath = "$binRootPath/aapt"
        aaptPath2 = "$binRootPath/aapt2"
        androidJarPath = "$binRootPath/android-framework.jar"
        this.decodedFilePath = decodedFilePath
        targetApkPath = apkPath
        resourceApkPath = "$decodedFilePath/build/resource.apk"
        LOGGER.info("aaptPath: $aaptPath")
        LOGGER.info("androidJarPath: $androidJarPath")
        LOGGER.info("decodedFilePath: " + this.decodedFilePath)
        stepInfo = TaskStepInfo()
    }

    override fun error(args: String?) {
        setNextStep(String.format("E: %s", args))
    }

    override fun log(level: Level, format: String?, ex: Throwable?) {
        val ch = level.name[0]
        val fmt = "%c: %s"
        format?.let {
            setNextStep(String.format(fmt, ch, format))
        }
        log(fmt, ch, ex)
    }

    private fun log(fmt: String, ch: Char, ex: Throwable?) {
        if (ex == null) {
            return
        }
        setNextStep(String.format(fmt, ch, ex.message))
        for (ste in ex.stackTrace) {
            setNextStep(String.format(fmt, ch, ste))
        }
        log(fmt, ch, ex.cause)
    }

    override fun fine(args: String?) {
//        setNextStep(String.format("F: %s", args))
    }

    override fun warning(args: String?) {
        setNextStep(String.format("W: %s", args))
    }

    override fun info(args: String?) {
        setNextStep(String.format("I: %s", args))
    }
}