package com.mcal.apkeditor;

import android.content.Context;
import android.util.Log;

import androidx.annotation.NonNull;

import com.mcal.apkeditor.ce.IApkMaking;
import com.mcal.apkeditor.pro.DexEncoder;
import com.mcal.apkeditor.smali.ISmaliAssembleCallback;
import com.mcal.apkeditor.utils.AssetsInstaller;
import com.mcal.apksigner.ApkSigner;
import com.mcal.common.data.Preferences;
import com.mcal.common.fastzip.FastZip;
import com.mcal.common.utils.CommandRunner;
import com.mcal.common.utils.FileUtils;
import com.mcal.common.utils.ITaskCallback;
import com.mcal.common.utils.ITaskCallback.TaskStepInfo;
import com.mcal.common.utils.LOGGER;
import com.mcal.common.utils.SDCard;

import java.io.File;
import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

import brut.androlib.Androlib;
import brut.androlib.options.BuildOptions;

public class ApkComposeThreadNew extends ComposeThread implements ISmaliAssembleCallback {

    private final Context ctx;

    private final String binRootPath;
    private final String aaptPath;
    private final String aaptPath2;
    private final String androidJarPath;
    private final String decodedFilePath;
    private final String targetApkPath; // Target APK path
    private final String resourceApkPath; // if res modified, store the apk generated by aapt
    // Record all the dex file replaces
    @NonNull
    private final Map<String, String> builtDexFiles = new HashMap<>();
    // Samli file modified or not
    @NonNull
    private final List<String> modifiedSmaliFolders = new ArrayList<>();
    private final TaskStepInfo stepInfo;
    // Last time updating the smali assemble info
    private final long lastUpdateAssembleTime = 0;
    // Before merge, call the extra maker
    @NonNull
    Map<String, String> replacedFiles = new HashMap<>();
    @NonNull
    Map<String, String> addedFiles = new HashMap<>();
    // Indicate succeed or not
    private boolean succeed;
    private String errMessage;
    private ITaskCallback taskCallback;
    // Flag to control run or not
    private boolean stopFlag = false;
    private boolean bSignApk;
    private IApkMaking extraMaker;

    /**
     * @param ctx             Context
     * @param decodedFilePath path store all the decoded files
     * @param apkPath         target apk path
     */
    public ApkComposeThreadNew(@NonNull Context ctx, String decodedFilePath, String apkPath) {
        this.ctx = ctx;

        File fileDir = ctx.getFilesDir();
        String rootDirectory = fileDir.getAbsolutePath();
        this.binRootPath = rootDirectory + "/bin";
        this.aaptPath = binRootPath + "/aapt";
        this.aaptPath2 = binRootPath + "/aapt2";
        this.androidJarPath = binRootPath + "/android-framework.jar";
        this.decodedFilePath = decodedFilePath;
        this.targetApkPath = apkPath;
        this.resourceApkPath = decodedFilePath + "/build/resource.apk";

        LOGGER.info("aaptPath: " + this.aaptPath);
        LOGGER.info("androidJarPath: " + this.androidJarPath);
        LOGGER.info("decodedFilePath: " + this.decodedFilePath);

        this.stepInfo = new TaskStepInfo();
    }

    // resReplaces contains non-xml replaces
    // resFileModified means res added/deleted, or xml changed
    @Override
    public void setModification(boolean strModified, boolean manifestModified,
                                boolean resFileModified, List<String> modifiedSmaliFolders,
                                Map<String, String> addedFiles, Map<String, String> replacedFiles,
                                Set<String> deletedFiles, Map<String, String> fileEntry2ZipEntry,
                                boolean bSignApk) {
        this.bSignApk = bSignApk;
    }

    @Override
    public void run() {
        long startTime = System.currentTimeMillis();
        // Make sure build directory is created
        File buildDir = new File(decodedFilePath + "/build");
        if (!buildDir.exists()) {
            if (buildDir.mkdir()) {
                Log.e(getClass().getName(), buildDir + " created");
            }
        }

        if (Preferences.isApkToolCompiler()) {
            do {
                //File framework = new File(ctx.getFilesDir() + "/bin/android-framework.jar");
                //File frameworkApk = new File(ctx.getFilesDir() + "/bin/1.apk");
                File binFolder = new File(ctx.getFilesDir() + "/bin");

                BuildOptions options = new BuildOptions();
                options.useAapt2 = Preferences.isAapt2(ctx);
                options.aaptPath = binFolder + File.separator + (Preferences.isAapt2(ctx) ? "aapt2" : "aapt");
                options.frameworkFolderLocation = binFolder.getPath();
                Androlib androlib = new Androlib(options);

                try {
                    File tmp = File.createTempFile("APKTOOL", null);

                    //if(!frameworkApk.exists() && frameworkApk.length() != 0) {
                    //    this.stepInfo.stepTotal = 5;
                    //    setNextStep("Installing Framework...");
                    //    androlib.installFramework(framework);
                    //} else {
                        this.stepInfo.stepTotal = 4;
                    //}

                    try {
                        setNextStep("Preparing...");
                        new AssetsInstaller(ctx).install();
                    } catch (Exception e) {
                        this.errMessage = e.getMessage();
                    }

                    setNextStep("Compiling...");
                    androlib.build(new File(decodedFilePath), tmp);

                    //setNextStep("Building...");
                    //androlib.buildApk(new File(decodedFilePath), new File(targetApkPath.replace(".apk", "_unsigned.apk")));

                    setNextStep("Signing...");
                    if (!signApk(tmp.getPath())) {
                        break;
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                    this.errMessage = e.getMessage();
                    break;
                }
                // Clean up
                if (stopFlag) {
                    this.errMessage = "User request to stop";
                    break;
                }
                setNextStep(ctx.getString(R.string.cleanup));
                cleanup();
                this.succeed = true;
            } while (false);
        } else {
            boolean rebuildResource = needRebuildResource();

            checkSmaliModification();

            this.stepInfo.stepTotal = 0;

            // Prepare
            stepInfo.stepTotal += 1;

            // Need to build resource
            if (rebuildResource) {
                stepInfo.stepTotal += 1;
            }
            // Merge
            stepInfo.stepTotal += 1;
            // For DEX assembling
            if (!modifiedSmaliFolders.isEmpty()) {
                stepInfo.stepTotal += modifiedSmaliFolders.size();
            }
            // Sign
            if (BuildConfig.WITH_SIGN && bSignApk) {
                this.stepInfo.stepTotal += 1;
            }
            // Cleanup
            this.stepInfo.stepTotal += 1;

            do {
                // XML/String/Manifest modified, requires re-compiling
                if (rebuildResource) {
                    if (stopFlag) {
                        this.errMessage = "User request to stop";
                        break;
                    }
                    setNextStep(ctx.getString(R.string.compose));

                    try {
                        setNextStep("Preparing...");
                        new AssetsInstaller(ctx).install();
                    } catch (Exception e) {
                        this.errMessage = e.getMessage();
                    }

                    // Compose resource and extract files
                    if (stopFlag) {
                        this.errMessage = "User request to stop";
                        break;
                    }
                    if (!composeResource()) {
                        break;
                    }
                }

                // Assemble DEX files
                builtDexFiles.clear();
                if (!modifiedSmaliFolders.isEmpty()) {
                    boolean assembleError = false;
                    for (String smaliFolder : modifiedSmaliFolders) {

                        String smaliPath = decodedFilePath + "/" + smaliFolder;
                        String dexName = getDexNameBySmaliFolder(smaliFolder);
                        setNextStep(ctx.getString(R.string.assemble_dex_file) + ": " + dexName);
                        try {
                            // Log.d("DEBUG", "Assemble " + smaliPath + " to " + dexName);
                            assembleSmali(smaliPath, dexName);
                        } catch (Throwable e) {
                            e.printStackTrace();
                            this.errMessage = e.getMessage();
                            assembleError = true;
                            break;
                        }

                        if (stopFlag) {
                            this.errMessage = "User request to stop";
                            assembleError = true;
                            break;
                        }
                    }

                    if (assembleError)
                        break;
                }

                // Merge
                if (stopFlag) {
                    this.errMessage = "User request to stop";
                    break;
                }
                setNextStep(ctx.getString(R.string.merge));

                try {
                    mergeApk();
                } catch (Exception e) {
                    e.printStackTrace();
                    this.errMessage = ctx.getString(R.string.merge) + ": " + e.getMessage();
                    break;
                }

                // Sign or not
                if (BuildConfig.WITH_SIGN && bSignApk) {
                    if (stopFlag) {
                        this.errMessage = "User request to stop";
                        break;
                    }
                    setNextStep(ctx.getString(R.string.sign));
                    if (!signApk(targetApkPath.replace(".apk", "_unsigned.apk"))) {
                        break;
                    }
                }

                // Clean up
                if (stopFlag) {
                    this.errMessage = "User request to stop";
                    break;
                }
                setNextStep(ctx.getString(R.string.cleanup));
                cleanup();

                // For free version, make sure it longer enough, so that ad could be loaded
                if (!BuildConfig.IS_PRO) {
                    long curTime = System.currentTimeMillis();
                    if (curTime - startTime < 7500) {
                        try {
                            Thread.sleep(7500 - (curTime - startTime));
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        }
                    }
                }

                this.succeed = true;
            } while (false);
        }
        if (!stopFlag) {
            if (succeed) {
                taskCallback.taskSucceed();
            } else {
                taskCallback.taskFailed(errMessage);
            }
        }
    }

    private long getLastModifyTime(@NonNull File file) {
        if (file.exists()) {
            return file.lastModified();
        }
        // If file does not exist, then return 0
        return 0;
    }

    // Collect all modified smali folders
    private void checkSmaliModification() {
        File decodeDir = new File(decodedFilePath);
        File[] files = decodeDir.listFiles();
        if (files != null) {
            for (File f : files) {
                if (!f.isDirectory()) {
                    continue;
                }

                String dirName = f.getName();
                if (dirName.equals("smali") || dirName.startsWith("smali_")) {
                    String dexName = getDexNameBySmaliFolder(dirName);
                    long dexTime1 = getLastModifyTime(
                            new File(decodedFilePath + "/" + dexName));
                    long dexTime2 = getLastModifyTime(
                            new File(decodedFilePath + "/build/" + dexName));
                    long dexTime = (Math.max(dexTime2, dexTime1));
                    long smaliTime = FileUtils.recursiveModifiedTime(f);
                    // Means smali code is modified
                    if (smaliTime > dexTime) {
                        this.modifiedSmaliFolders.add(dirName);
                    }
                }
            }
        }
    }

    @NonNull
    private String getDexNameBySmaliFolder(String smaliFolder) {
        if ("smali".equals(smaliFolder)) {
            return "classes.dex";
        }
        if (smaliFolder.startsWith("smali_")) {
            return smaliFolder.substring("smali_".length()) + ".dex";
        }
        return smaliFolder + ".dex";
    }

    private void setNextStep(String description) {
        stepInfo.stepIndex += 1;
        stepInfo.stepDescription = description;
        taskCallback.setTaskStepInfo(stepInfo);
    }

    // Assemble smali to DEX (build/classes.dex)
    private void assembleSmali(String smaliFilePath, String dexFileName)
            throws Throwable {
        File decodeDir = new File(decodedFilePath);
        File buildDir = new File(decodeDir, "build");
        if (!buildDir.exists()) {
            if (buildDir.mkdir()) {
                Log.e(getClass().getName(), buildDir + " created");
            }
        }

        File dexFile = new File(buildDir, dexFileName);
        String dexFilePath = dexFile.getPath();

        // Log.d("DEBUG", "assemble " + smaliFilePath + " to " + dexFilePath +
        // ", dexFileName=" + dexFileName);

        // Invoke DexEncoder.smali2Dex
        try {
            long start = System.currentTimeMillis();
            DexEncoder.smali2Dex(smaliFilePath, dexFilePath, this);

            Log.i("DEBUG", "Encode time=" + (System.currentTimeMillis() - start));

            // Record built dex files
            this.builtDexFiles.put(dexFileName, dexFilePath);
        } catch (InvocationTargetException e) {
            throw e.getTargetException();
        }
    }

    private void cleanup() {
        // Delete all the decoded files
        // Do not delete the res directory any more, as the project must keep it
        CommandRunner cr = new CommandRunner();
//        cr.runCommand("rm -rf " + decodedFilePath + "/res", null, 10000);

        // Clean /sdcard/ApkEditor/tmp
        try {
            String tmpDir = SDCard.getRootDirectory() + "/ApkEditor/tmp";
            cr.runCommand("rm -rf " + tmpDir, null, 10000);
        } catch (Exception ignored) {
        }

        // Log.d("DEBUG", "decodedFilePath" + decodedFilePath);
    }

    private void mergeApk() {
        if (this.extraMaker != null) {
            try {
                extraMaker.prepareReplaces(ctx, resourceApkPath, replacedFiles,
                        // Note: currently not support description update
                        strDesc -> {
                        });
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        //Map<String, String> filesToAdd = new HashMap<>();

        // Collect files need to be added

        File assetsDir = new File(decodedFilePath + "/assets");
        if (assetsDir.exists()) {
            collectFiles(addedFiles, assetsDir, "assets/");
        }
        File libDir = new File(decodedFilePath + "/lib");
        if (libDir.exists()) {
            collectFiles(addedFiles, libDir, "lib/");
        }
        File libsDir = new File(decodedFilePath + "/libs");
        if (libsDir.exists()) {
            collectFiles(addedFiles, libsDir, "libs/");
        }
        //File kotlinDir = new File(decodedFilePath + "/kotlin");
        //if (kotlinDir.exists()) {
        //    collectFiles(addedFiles, kotlinDir, "kotlin/");
        //}
        File unknownDir = new File(decodedFilePath + "/unknown");
        if (unknownDir.exists()) {
            collectFiles(addedFiles, unknownDir, "");
        }
        // DEX
        collectDexFiles(addedFiles);

        // Transform to string
        StringBuilder sb = new StringBuilder();
        int addLen = 0;
        for (Map.Entry<String, String> entry : addedFiles.entrySet()) {
            String key = entry.getKey();
            String value = entry.getValue();
            sb.append(key);
            sb.append('\n');
            sb.append(value);
            sb.append('\n');
            addLen += key.getBytes().length + value.getBytes().length + 2;
        }

        StringBuilder sb2 = new StringBuilder();
        int replaceLen = 0;
        for (Map.Entry<String, String> entry : replacedFiles.entrySet()) {
            String key = entry.getKey();
            String value = entry.getValue();
            sb2.append(key);
            sb2.append('\n');
            sb2.append(value);
            sb2.append('\n');
            replaceLen += key.getBytes().length + value.getBytes().length + 2;
        }

        //MainActivity.md(targetApkPath, resourceApkPath, sb.toString(), addLen, "", 0, sb2.toString(), replaceLen);
        try {
            FastZip.repack(resourceApkPath, targetApkPath.replace(".apk", "_unsigned.apk"), replacedFiles, addedFiles, null);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void collectDexFiles(@NonNull Map<String, String> filesToAdd) {
        filesToAdd.putAll(this.builtDexFiles);

        File decodeDir = new File(decodedFilePath);
        File[] files = decodeDir.listFiles();
        if (files != null) {
            for (File f : files) {
                String name = f.getName();
                if (f.isFile() && name.endsWith(".dex")) {
                    File dex = new File(decodedFilePath + "/build/" + name);
                    if (dex.isFile() && dex.exists()) {
                        filesToAdd.put(name, dex.getPath());
                        replacedFiles.put(name, dex.getPath());
                    } else {
                        filesToAdd.put(name, f.getPath());
                        replacedFiles.put(name, f.getPath());
                    }
                }
            }
        }
    }

    private void collectFiles(Map<String, String> relPath2AbsPath, @NonNull File dir, String relPath) {
        File[] files = dir.listFiles();
        if (files != null) {
            for (File f : files) {
                if (f.isFile()) {
                    relPath2AbsPath.put(relPath + f.getName(), f.getPath());
                    replacedFiles.put(relPath + f.getName(), f.getPath());
                } else if (f.isDirectory()) {
                    collectFiles(relPath2AbsPath, f, relPath + f.getName() + "/");
                }
            }
        }
    }

    private boolean needRebuildResource() {
        boolean buildResource = true;

        // To check if need to build the resource
        File apkFile = new File(resourceApkPath);
        if (apkFile.isFile() && apkFile.exists()) {
            long resModifyTime = FileUtils.recursiveModifiedTime(new File[]{
                    new File(decodedFilePath + "/res"),
                    new File(decodedFilePath + "/AndroidManifest.xml")});
            long apkTime = apkFile.lastModified();
            if (apkTime > resModifyTime) {
                buildResource = false;
            }
        }

        return buildResource;
    }

    private boolean signApk(String inApk) {
        try {
            new ApkSigner().signApk(inApk, targetApkPath);
            return true;
        } catch (Exception e) {
            String strHeader = ctx.getResources().getString(R.string.sign_error);
            this.errMessage = strHeader + e.getMessage();
        }

        return false;
    }

    private boolean composeResource() {
        try {
            return Preferences.isAapt2(ctx) ? aapt2() : aapt();
        } catch (IOException e) {
            e.printStackTrace();
            return false;
        }
    }

    private boolean aapt() {
        boolean noVersionVectorOption = Preferences.getNoVersionVectorOption(aaptPath);

        List<String> paramList = new ArrayList<>();
        paramList.add(aaptPath);
        paramList.add("package");
        paramList.add("-f");
        paramList.add("-I");
        paramList.add(androidJarPath);
        paramList.add("-S");
        paramList.add(decodedFilePath + "/res");
        paramList.add("-M");
        paramList.add(decodedFilePath + "/AndroidManifest.xml");
        paramList.add("-F");
        paramList.add(resourceApkPath);
        if (noVersionVectorOption) {
            paramList.add("--no-version-vectors");
        }

        CommandRunner cr = new CommandRunner();
        boolean ret = cr.runCommand(paramList.toArray(new String[0]),
                null, null, 300 * 1000, true);
        //Log.e("DEBUG", "aapt Time: " + (System.currentTimeMillis() - startTime) / 1000.0 + " seconds");

        LOGGER.info("stdout: " + cr.getStdOut() + ", ret=" + ret);
        if (!ret) {
            LOGGER.info("stderr: " + cr.getStdError());
            this.errMessage = cr.getStdError();
            return false;
        }
        return true;
    }

    public boolean aapt2() throws IOException {
        boolean noVersionVectorOption = Preferences.getNoVersionVectorOption(aaptPath2);

        ArrayList<String> args = new ArrayList<>();
        //compile resources

        args.add(aaptPath2);
        args.add("compile");
        args.add("--dir");
        args.add(decodedFilePath + "/res");
        args.add("-o");

        File resPath = new File(decodedFilePath, "build");
        if (resPath.mkdir()) {
            Log.e(getClass().getName(), new File(decodedFilePath, "build") + "created");
        }

        File outputPath = com.mcal.apkeditor.utils.FileUtils.createNewFile(resPath, "resources.zip");

        args.add(outputPath.getAbsolutePath());


        long startTime = System.currentTimeMillis();
        CommandRunner cr = new CommandRunner();
        boolean ret = cr.runCommand(args.toArray(new String[0]),
                null, null, 300 * 1000, true);

        LOGGER.info("stdout: " + cr.getStdOut() + ", ret=" + ret);
        if (!ret) {
            LOGGER.info("stderr: " + cr.getStdError());
            this.errMessage = cr.getStdError();
            return false;
        }

        args.clear();

        //link resources

        args.add(aaptPath2);
        args.add("link");
        args.add("--allow-reserved-package-id");
        if (noVersionVectorOption) {
            args.add("--no-version-vectors");
        }
        args.add("--no-version-transitions");
        args.add("--auto-add-overlay");

        args.add("-I");
        args.add(androidJarPath);

        //add compiled resources
        File[] resources = resPath.listFiles();
        if (resources != null) {
            for (File file : resources) {
                if (file.isDirectory() || file.getName().equals("resources.zip")) {
                    continue;
                }
                args.add("-R");
                args.add(file.getAbsolutePath());
            }
        }

        File projectZip = new File(resPath, "resources.zip");
        if (projectZip.exists()) {
            args.add("-R");
            args.add(projectZip.getAbsolutePath());
        }

        args.add("--manifest");
        args.add(decodedFilePath + "/AndroidManifest.xml");

        args.add("-o");
        args.add(resourceApkPath);

        CommandRunner cr2 = new CommandRunner();
        boolean ret2 = cr2.runCommand(args.toArray(new String[0]),
                null, null, 300 * 1000, true);
        Log.e("DEBUG", "aapt Time: " + (System.currentTimeMillis() - startTime) / 1000.0 + " seconds");

        LOGGER.info("stdout: " + cr2.getStdOut() + ", ret=" + ret2);
        if (!ret2) {
            LOGGER.info("stderr: " + cr2.getStdError());
            this.errMessage = cr.getStdError();
            return false;
        }
        return true;
    }

    @Override
    public void setTaskCallback(ITaskCallback taskCallback) {
        this.taskCallback = taskCallback;
    }

    @Override
    public void updateAssembledFiles(int assembledFiles, int totalFiles) {
        long curTime = System.currentTimeMillis();
        if (curTime > this.lastUpdateAssembleTime + 500) {
            String fmt = ctx.getString(R.string.assemble_dex_detail);
            stepInfo.stepDescription = String.format(fmt, assembledFiles,
                    totalFiles);
            taskCallback.setTaskStepInfo(stepInfo);
        }
    }

    @Override
    public void stopRunning() {
        this.stopFlag = true;
        this.interrupt();
    }

    @Override
    public void setExtraMaker(IApkMaking extraMaker) {
        this.extraMaker = extraMaker;
    }

    public String getErrMessage() {
        return errMessage;
    }
}
