plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

android {
    compileSdk project.compileSDK.toInteger()

    defaultConfig {
        minSdk project.minSDK.toInteger()
        targetSdk project.targetSDK.toInteger()
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    buildFeatures {
        viewBinding true
    }
    namespace 'com.mcal.bshengine'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation project(":core")
    implementation project(":melissa")
    implementation project(":feature:code-editor")
    implementation project(":jadx:jadx-core")
    implementation project(":jadx:jadx-plugins:jadx-smali-input")

    implementation("com.github.TimScriptov.App-UI-Designer:webview:1.0.9")

    implementation("com.github.TimScriptov:Android-ApkTool-Library:2.7.0.5")
    implementation("org.smali:baksmali:2.5.2")
    implementation("org.smali:dexlib2:2.5.2")
    implementation("org.smali:smali:2.5.2")

    implementation("androidx.core:core-ktx:1.9.0")
    implementation("androidx.appcompat:appcompat:1.6.1")
    implementation("com.google.android.material:material:1.8.0")

    implementation("com.mikepenz:fastadapter:5.7.0")
    implementation("com.mikepenz:fastadapter-extensions-binding:5.7.0")
    implementation("me.zhanghai.android.fastscroll:library:1.2.0")

    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.1")
}