plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

android {
    compileSdk project.compileSDK.toInteger()

    defaultConfig {
        minSdk project.minSDK.toInteger()
        targetSdk project.targetSDK.toInteger()
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    buildFeatures {
        viewBinding true
    }
    namespace 'com.mcal.bshengine'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation project(":core")
    implementation project(':feature:code-editor')
    implementation project(":melissa")

    implementation mcal.webview
    implementation mcal.webview

    implementation tools.apktool

    implementation jetpack.core
    implementation jetpack.appcompat
    implementation jetpack.material

    implementation ui.fastadapter
    implementation ui.fastadapter.binding
    implementation ui.fastscroll

    implementation misc.coroutines.core
}