plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

android {
    compileSdk project.compileSDK.toInteger()

    defaultConfig {
        minSdk project.minSDK.toInteger()
        targetSdk project.targetSDK.toInteger()
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    namespace 'com.mcal.patchview'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation project(':core')

    implementation 'org.jetbrains:annotations:23.1.0'

    implementation("androidx.core:core-ktx:1.9.0")
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation("androidx.preference:preference-ktx:1.2.0")
}