plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

android {
    compileSdk project.compileSDK.toInteger()

    defaultConfig {
        minSdk project.minSDK.toInteger()
        targetSdk project.targetSDK.toInteger()
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
    packagingOptions {
        resources.excludes += 'license/*'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }
    buildFeatures {
        viewBinding true
    }
    namespace 'com.mcal.neweditor'
}

dependencies {
    implementation project(':core')
    implementation project(':jadx:jadx-core')
    implementation project(':jadx:jadx-plugins:jadx-dex-input')
    implementation project(':jadx:jadx-plugins:jadx-smali-input')
    implementation project(':melissa')
    implementation project(':feature:colormixer')
    implementation project(':feature:permission-editor')
    implementation("com.github.TimScriptov.App-UI-Designer:uidesigner:1.0.9")
    implementation("com.google.guava:guava:31.0.1-android")

    implementation("org.smali:baksmali:2.5.2")
    implementation("org.smali:dexlib2:2.5.2")
    implementation("org.smali:smali:2.5.2")
    implementation("androidx.appcompat:appcompat:1.6.1")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.5.1")

    implementation("com.google.android.material:material:1.8.0")

    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.1")

    implementation("io.github.Rosemoe.sora-editor:editor:0.21.0")
    implementation("io.github.Rosemoe.sora-editor:language-java:0.21.0")
    implementation("io.github.Rosemoe.sora-editor:language-textmate:0.21.0")
    implementation("io.github.Rosemoe.sora-editor:editor-lsp:0.21.0")
}