plugins {
	id 'com.android.library'
}

android {
	compileSdk project.compileSDK.toInteger()

	defaultConfig {
		minSdk project.minSDK.toInteger()
		targetSdk project.targetSDK.toInteger()
	}

	buildTypes {
		release {
			minifyEnabled false
			proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
		}
	}
	namespace 'com.mcal.jadx.jadx_plugin_dex_input'
	compileOptions {
		sourceCompatibility JavaVersion.VERSION_17
		targetCompatibility JavaVersion.VERSION_17
	}
}

dependencies {
	implementation("org.smali:dexlib2:2.5.2")
	implementation("org.smali:smali:2.5.2")
	implementation("org.smali:baksmali:2.5.2")

	api(project(":jadx:jadx-plugins:jadx-plugins-api"))

	// force latest version for smali
	constraints {
		implementation 'com.google.guava:guava:31.1-android'
		implementation 'com.beust:jcommander:1.81'
	}

	implementation 'org.jetbrains:annotations:24.0.1'
	implementation 'org.slf4j:slf4j-api:2.0.3'
}
