plugins {
	id 'com.android.library'
}

android {
	compileSdk project.compileSDK.toInteger()

	defaultConfig {
		minSdk project.minSDK.toInteger()
		targetSdk project.targetSDK.toInteger()
	}

	buildTypes {
		release {
			minifyEnabled false
			proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
		}
	}
	namespace 'com.mcal.jadx.jadx_cli'
}

dependencies {
	implementation(project(':jadx:jadx-core'))

	runtimeOnly(project(':jadx:jadx-plugins:jadx-dex-input'))
	runtimeOnly(project(':jadx:jadx-plugins:jadx-java-input'))
	runtimeOnly(project(':jadx:jadx-plugins:jadx-java-convert'))
	runtimeOnly(project(':jadx:jadx-plugins:jadx-smali-input'))

	implementation 'com.beust:jcommander:1.82'
	implementation 'ch.qos.logback:logback-classic:1.3.0'
	implementation 'org.jetbrains:annotations:23.1.0'
}