plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

android {
    compileSdk 32

    defaultConfig {
        minSdk 14
        targetSdk 32
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    namespace 'com.mcal.apksigner'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    api project(':libraries')
    implementation project(':core')
    implementation project(':sun')

    implementation 'androidx.appcompat:appcompat:1.5.0'

    implementation 'com.google.android.material:material:1.6.1'

    implementation 'com.madgag.spongycastle:core:1.58.0.0'
    implementation 'com.madgag.spongycastle:prov:1.58.0.0'

    implementation 'org.jetbrains:annotations:23.0.0'
    implementation 'androidx.annotation:annotation:1.4.0'

    implementation 'org.conscrypt:conscrypt-android:2.5.2'
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.6.4"
}