plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

android {
    compileSdk project.compileSDK.toInteger()

    defaultConfig {
        minSdk project.minSDK.toInteger()
        targetSdk project.targetSDK.toInteger()
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    namespace 'com.mcal.apksigner'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    api project(flat.jars)
    implementation project(flat.core)
    implementation project(flat.sun)

    implementation signing.spongy_core
    implementation signing.spongy_prov

    implementation misc.annotations
    implementation misc.annotations_android

    implementation signing.conscrypt
    implementation misc.coroutines_java
}