plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

android {
    compileSdk project.compileSDK.toInteger()

    defaultConfig {
        minSdk project.minSDK.toInteger()
        targetSdk project.targetSDK.toInteger()
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
    buildFeatures {
        viewBinding true
    }
    namespace 'com.mcal.appdm.base'
}

dependencies {
    implementation project(':core')
    api project(':feature:sqliteutil')
    api project(':feature:code-editor')
    implementation project(":melissa")

    implementation jetpack.appcompat

    implementation jetpack.material

    implementation misc.annotations
}